### ISSUE TITLE
Add angular conversion functions to standard environment

### ISSUE THREAD

**Issue by jakerockland** [jakerockland/Swisp#24]
Functions to add: 
- [x] degrees
- [x] radians

**Comment by sarthakkapoor21** [comment]
Hey jakerockland, I'm interested! How do I get started?

**Comment by jakerockland** [comment]
@sarthakkapoor21 Awesome! 😄 Following this PR as a guide is probably the way to go: https://github.com/jakerockland/Swisp/pull/28
