### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by zaoqi** [jakerockland/Swisp#39]
```scheme
(define (f) f)
```
ARC does not support local recursive functions

**Comment by jakerockland** [comment]
Hi @zaoqi! Bit confused what the issue is here?

**Comment by jakerockland** [comment]
Going to close this for now as I'm not sure what the issue at hand is, can reopen though if you can add a bit more clarification @zaoqi 😅

**Comment by zaoqi-unsafe** [comment]
Arc doesn't supports something like it.

**Comment by jakerockland** [comment]
Ah, will need to look into this a bit more @zaoqi-unsafe

**Comment by zaoqi** [comment]
can combine functions to solve this problem

**Comment by jakerockland** [comment]
@zaoqi Unfortunately I am not having the time recently to work on this, but if you have the time to open up a PR, I would very much appreciate it and will review ASAP!

**Comment by jakerockland** [comment]
@zaoqi Would you be able to provide a bit more info regarding what you mean by combining functions to fix this?

**Comment by jakerockland** [comment]
@zaoqi Wanted to ping you again just to see if you could give a bit more insight to me for fixing this, any resources you can point me in the direction of would be much appreciated!

**Comment by zaoqi** [comment]
ARC cannot handle recursion.

I invented a way to solve it.But it may not be suitable for Scheme.

This bug is not important and does not need to be resolved.

**Comment by jakerockland** [comment]
@zaoqi Hmm okay thanks so much for shining some light on this! I really appreciate it. Going to close this issue for now then though.
